# Generated by Django 6.0.1 on 2026-01-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_category_options_cars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
